export type DetectionDTO = {
	mjd: number;
	candid: string;
	fid: number;
	pid: number;
	diffmaglim: number;
	isdiffpos: number;
	nid: number;
	distnr: number;
	magpsf: number;
	magpsf_corr: number;
	magpsf_corr_ext: null;
	magap: number;
	magap_corr: number | null;
	sigmapsf: number;
	sigmapsf_corr: number;
	sigmapsf_corr_ext: number;
	sigmagap: number;
	sigmagap_corr: number | null;
	ra: number;
	dec: number;
	rb: number;
	rbversion: string;
	drb: number | null;
	magapbig: number;
	sigmagapbig: number;
	rfid: number | null;
	has_stamp: boolean;
	corrected: boolean;
	dubious: boolean;
	candid_alert: null;
	step_id_corr: string;
	phase: null;
	parent_candid: number;
}

export type Detection = {
	mjd: number;
	candid: string;
	fid: number;
	pid: number;
	diffmaglim: number;
	isdiffpos: number;
	nid: number;
	distnr: number;
	magpsf: number;
	magpsfCorr: number;
	magpsfCorrExt: null;
	magap: number;
	magapCorr: number | null;
	sigmapsf: number;
	sigmapsfCorr: number;
	sigmapsfCorrExt: number;
	sigmagap: number;
	sigmagapCorr: number | null;
	ra: number;
	dec: number;
	rb: number;
	rbversion: string;
	drb: number | null;
	magapbig: number;
	sigmagapbig: number;
	rfid: number | null;
	hasStamp: boolean;
	corrected: boolean;
	dubious: boolean;
	candidAlert: null;
	stepIdCorr: string;
	phase: null;
	parentCandid: number;
}